/* Dihasilkan oleh tools/gen_extensions.py - JANGAN DIEDIT MANUAL. */
/* Divalidasi: tiap ekstensi di sini punya entry point lengkap. */

#define ORYON_EXTENSIONS \
    "GL_ARB_compatibility " \
    "GL_ARB_depth_buffer_float " \
    "GL_ARB_depth_texture " \
    "GL_ARB_explicit_attrib_location " \
    "GL_ARB_fragment_shader " \
    "GL_ARB_framebuffer_object " \
    "GL_ARB_framebuffer_sRGB " \
    "GL_ARB_half_float_pixel " \
    "GL_ARB_half_float_vertex " \
    "GL_ARB_map_buffer_alignment " \
    "GL_ARB_pixel_buffer_object " \
    "GL_ARB_seamless_cube_map " \
    "GL_ARB_shadow " \
    "GL_ARB_texture_border_clamp " \
    "GL_ARB_texture_cube_map " \
    "GL_ARB_texture_env_combine " \
    "GL_ARB_texture_non_power_of_two " \
    "GL_EXT_blend_func_separate " \
    "GL_EXT_blend_subtract " \
    "GL_EXT_framebuffer_sRGB " \
    "GL_EXT_packed_depth_stencil " \
    "GL_EXT_rescale_normal " \
    "GL_EXT_stencil_wrap " \
    "GL_EXT_texture_lod_bias " \
    "GL_EXT_texture_sRGB"
